apiVersion: v1
kind: ConfigMap
metadata:
  name: pdb-config
data:
  POSTGRES_DB: {{ .Values.postgresql.db }}
  POSTGRES_USER: {{ .Values.postgresql.user }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pdb-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-deploy
  labels:
    app: pdb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pdb
    spec:
      containers:
        - name: pdb-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: pdb
          envFrom:
            - configMapRef:
                name: pdb-config
            - secretRef:
                name: pdb-secret
          volumeMounts:
            - name: pdb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: pdb-data
          persistentVolumeClaim:
            claimName: pdb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: pdb-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: pdb
