apiVersion: v1
kind: ConfigMap
metadata:
  name: pdb-config
  namespace: db12
 
data:
  POSTGRES_DB: kishna
  POSTGRES_USER: kishna

---
apiVersion: v1
kind: Secret
metadata:
  name: pdb-secret
  namespace: db12
 
type: Opaque
data:
  POSTGRES_PASSWORD: d3BwYXNzd29yZA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-deploy
  namespace: db12
  labels:
    app: pdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pdb
    spec:
      containers:
      - name: pdb-container
        image: postgres:13
        ports:
        - containerPort: 5432
          name: pdb
        envFrom:
        - configMapRef:
            name: pdb-config
        - secretRef:
            name: pdb-secret
        volumeMounts:
        - name: pdb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: pdb-data
        persistentVolumeClaim:
          claimName: pdb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdb-pvc
  namespace: db12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: pdb-service
  namespace: db12
 
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pdb
